import Layout from "@/components/Layout"
export const metadata = {
  title: 'Land Area Converter',
  description: 'Generated by create next app',
}

export default function LandAreaLayout({ children }) {

  return <Layout>{children} </Layout> 
}

