import Layout from "@/components/Layout"
export const metadata = {
  title: 'VAT & TAX',
  description: 'Generated by create next app',
}

export default function VatTaxLayout({ children }) {

  return <Layout>{children} </Layout> 
}

