import Layout from "@/components/Layout"
export const metadata = {
  title: 'Database Restore',
  description: 'Generated by create next app',
}

export default function RestoreLayout({ children }) {

  return <Layout>{children} </Layout> 
}

