import Layout from "@/components/Layout"
export const metadata = {
    title: 'Localta',
    description: 'Generated by create next app',
}

export default function LocaltaLayout({ children }) {
    return <Layout>{children} </Layout>
}

