import Layout from "@/components/Layout"
export const metadata = {
  title: 'Price',
  description: 'Generated by create next app',
}

export default function PriceLayout({ children }) {

  return <Layout>{children} </Layout> 
}

