import Layout from "@/components/Layout"
export const metadata = {
  title: 'District',
  description: 'Generated by create next app',
}

export default function DistrictLayout({ children }) {

  return <Layout>{children} </Layout> 
}

