import Layout from "@/components/Layout"
export const metadata = {
  title: 'Mobile',
  description: 'Generated by create next app',
}

export default function MobileLayout({ children }) {

  return <Layout>{children} </Layout> 
}

