import Layout from "@/components/Layout"
export const metadata = {
  title: 'Rent',
  description: 'Generated by create next app',
}

export default function RentLayout({ children }) {

  return <Layout>{children} </Layout> 
}

