import Layout from "@/components/Layout"
export const metadata = {
  title: 'Project',
  description: 'Generated by create next app',
}

export default function ProjectLayout({ children }) {

  return <Layout>{children} </Layout> 
}

