import Layout from "@/components/Layout"
export const metadata = {
    title: 'Bayprostab',
    description: 'Generated by create next app',
}

export default function BayprostabLayout({ children }) {

    return <Layout>{children} </Layout>
}

