import Layout from "@/components/Layout"
export const metadata = {
  title: 'Construction',
  description: 'Generated by create next app',
}

export default function ConstructionLayout({ children }) {

  return <Layout>{children} </Layout> 
}

