import Layout from "@/components/Layout"
export const metadata = {
  title: 'Unit',
  description: 'Generated by create next app',
}

export default function UnitLayout({ children }) {

  return <Layout>{children} </Layout> 
}

