import Layout from "@/components/Layout"
export const metadata = {
  title: 'DA',
  description: 'Generated by create next app',
}

export default function DaLayout({ children }) {

  return <Layout>{children} </Layout> 
}

