import Layout from "@/components/Layout"
export const metadata = {
  title: 'Staff Benefit',
  description: 'Generated by create next app',
}

export default function BenefitLayout({ children }) {

  return <Layout>{children} </Layout> 
}

