import Layout from "@/components/Layout"
export const metadata = {
  title: 'Octen',
  description: 'Generated by create next app',
}

export default function OctenLayout({ children }) {
  return <Layout>{children} </Layout>
}