import Layout from "@/components/Layout"
export const metadata = {
  title: 'Place',
  description: 'Generated by create next app',
}

export default function PlaceLayout({ children }) {

  return <Layout>{children} </Layout> 
}

