import Layout from "@/components/Layout"
export const metadata = {
  title: 'Author',
  description: 'Generated by create next app',
}

export default function AuthorLayout({ children }) {

  return <Layout>{children} </Layout> 
}

