import Layout from "@/components/Layout"
export const metadata = {
  title: 'Staff',
  description: 'Generated by create next app',
}

export default function StaffLayout({ children }) {

  return <Layout>{children} </Layout> 
}

