import Layout from "@/components/Layout"
export const metadata = {
    title: 'Tabill',
    description: 'Generated by create next app',
}

export default function TabillLayout({ children }) {

    return <Layout>{children} </Layout>
}

