import Layout from "@/components/Layout"
export const metadata = {
  title: 'Bkash',
  description: 'Generated by create next app',
}

export default function BkashLayout({ children }) {

  return <Layout>{children} </Layout> 
}

