import Layout from "@/components/Layout"
export const metadata = {
  title: 'TA',
  description: 'Generated by create next app',
}

export default function TaLayout({ children }) {

  return <Layout>{children} </Layout> 
}

