import Layout from "@/components/Layout"
export const metadata = {
    title: 'Electrick Bill',
    description: 'Generated by create next app',
}

export default function ElectrickbillLayout({ children }) {

    return <Layout>{children} </Layout>
}

